(ns credit.kernels.kotoba-oracle-gen
  "Regenerate the shipped decision core from `src/credit/kernels/*.kotoba`.

      clojure -M:dev:test:gen

  Runs under `:test` because the compiler lives there and must not reach a
  consumer. What it writes IS what `credit.kernels.gate` loads, so nothing
  here transforms it: the same `compile-source` call the drift gate makes,
  the same value, printed. If this file and that gate disagreed about how
  to compile, the gate would be checking something other than what ships.

  It writes a `.cljc` rather than an EDN resource for the reason
  `credit.kernels.kotoba-oracle`'s docstring gives: this actor decides
  inside a Cloudflare Worker and under `cljs.main`, and neither has a
  classpath to read a resource from."
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [kotoba.compiler.core :as compiler])
  (:gen-class))

(def cores
  "Oracle id -> the `.kotoba` it is compiled from, relative to the repo
  root. Declared here rather than beside `credit.kernels.kotoba-oracle/
  shipped` for one blunt reason: this namespace WRITES that one's
  dependency, so it cannot require it and still be able to run the first
  time. `credit.kernels.kotoba-oracle-test` requires both and demands the
  two id sets match."
  {:gate "src/credit/kernels/gate.kotoba"})

(def target
  "The portable target the shipped KIR is compiled for.

  KIR is target-independent for this core -- it is scalars, a flat record
  and `if`, well inside the native word-typed slice -- but ONE of them has
  to be the artifact, and naming it here rather than in two places is what
  keeps regeneration reproducible."
  :wasm32-kotoba-v1)

(def artifact-ns
  "Oracle id -> the namespace that carries its compiled KIR, and the file
  that namespace lives in."
  {:gate {:ns 'credit.kernels.gate-kir
          :path "src/credit/kernels/gate_kir.cljc"}})

(defn compile-text
  "Compile `.kotoba` source TEXT to KIR. The one call the drift gate also
  makes, and the one the delegation gate makes for its substitute core --
  both go through here so neither can be compiling something other than
  what ships."
  [source-text]
  (let [result (compiler/compile-source source-text target {})]
    (or (:kir result)
        (throw (ex-info "compile-source returned no :kir"
                        {:head (subs source-text 0 (min 80 (count source-text)))})))))

(defn compile-kir
  "Compile a `.kotoba` source file to KIR."
  [source-path]
  (compile-text (slurp (io/file source-path))))

(defn- artifact-source
  "The text of the generated namespace. Namespace-map printing is off: the
  artifact is read by three different readers and `#:credit.kernels{…}` is
  a compression, not a value."
  [id sym source-path k]
  (binding [*print-namespace-maps* false]
    (str ";; GENERATED by `clojure -M:dev:test:gen`"
         " (credit.kernels.kotoba-oracle-gen). DO NOT EDIT.\n"
         ";;\n"
         ";; This is `" source-path "` compiled: the credit governor's\n"
         ";; decision core as `credit.kernels.gate` actually runs it, through\n"
         ";; `credit.kernels.kotoba-oracle`. Editing it by hand makes the\n"
         ";; deployed rules differ from the source they are supposed to be,\n"
         ";; which is what `credit.kernels.kotoba-oracle-test` refuses.\n"
         ";;\n"
         ";; A namespace rather than an EDN resource because this actor\n"
         ";; decides inside a Cloudflare Worker and under `cljs.main`, and\n"
         ";; neither has a classpath.\n"
         "(ns " sym "\n"
         "  \"Compiled KIR for oracle " id ". Generated -- see the header.\")\n"
         "\n"
         "(def kir\n"
         "  \"`" source-path "`, compiled for " target ".\"\n"
         "  '"
         (with-out-str (pp/pprint k))
         ")\n")))

(defn write-artifact! [id]
  (let [{:keys [ns path]} (get artifact-ns id)
        source-path (get cores id)]
    (io/make-parents (io/file path))
    (spit path (artifact-source id ns source-path (compile-kir source-path)))
    path))

(defn regenerate-all! []
  (mapv (fn [[id _]] (write-artifact! id)) (sort-by key cores)))

(defn -main [& _]
  (run! println (regenerate-all!))
  (shutdown-agents))
