;; GENERATED by `clojure -M:dev:test:gen` (credit.kernels.kotoba-oracle-gen). DO NOT EDIT.
;;
;; This is `src/credit/kernels/gate.kotoba` compiled: the credit governor's
;; decision core as `credit.kernels.gate` actually runs it, through
;; `credit.kernels.kotoba-oracle`. Editing it by hand makes the
;; deployed rules differ from the source they are supposed to be,
;; which is what `credit.kernels.kotoba-oracle-test` refuses.
;;
;; A namespace rather than an EDN resource because this actor
;; decides inside a Cloudflare Worker and under `cljs.main`, and
;; neither has a classpath.
(ns credit.kernels.gate-kir
  "Compiled KIR for oracle :gate. Generated -- see the header.")

(def kir
  "`src/credit/kernels/gate.kotoba`, compiled for :wasm32-kotoba-v1."
  '{:format :kotoba.kir/v4,
 :signature nil,
 :functions
 [{:name confidence-floor-x100,
   :params [],
   :result :i64,
   :effects #{},
   :body 60,
   :param-types []}
  {:name affordability-ceiling-x100,
   :params [],
   :result :i64,
   :effects #{},
   :body 43,
   :param-types []}
  {:name norm-flag,
   :params [a],
   :result :i64,
   :effects #{},
   :body (if (= a 0) 0 1),
   :param-types [:i64]}
  {:name or2,
   :params [a b],
   :result :i64,
   :effects #{},
   :body (if (= a 1) 1 (if (= b 1) 1 0)),
   :param-types [:i64 :i64]}
  {:name confidence-low,
   :params [x100],
   :result :i64,
   :effects #{},
   :body
   (if
    (< x100 0)
    1
    (if (< 100 x100) 1 (if (< x100 (confidence-floor-x100)) 1 0))),
   :param-types [:i64]}
  {:name affordability-exceeded,
   :params [applicable total income],
   :result :i64,
   :effects #{},
   :body
   (if
    (= (norm-flag applicable) 0)
    0
    (if
     (< income 1)
     1
     (if
      (< total 0)
      1
      (if
       (< (* (affordability-ceiling-x100) income) (* 100 total))
       1
       0)))),
   :param-types [:i64 :i64 :i64]}
  {:name hard-violation,
   :params [proposal],
   :result :i64,
   :effects #{},
   :body
   (or2
    (or2
     (or2
      (norm-flag
       (record-get
        [:record
         :credit.kernels/proposal
         [[:spec-missing :i64]
          [:evidence-incomplete :i64]
          [:not-approved :i64]
          [:double-disb :i64]
          [:afford-applicable :i64]
          [:afford-total :i64]
          [:afford-income :i64]
          [:confidence-x100 :i64]
          [:actuation :i64]]]
        proposal
        :spec-missing))
      (norm-flag
       (record-get
        [:record
         :credit.kernels/proposal
         [[:spec-missing :i64]
          [:evidence-incomplete :i64]
          [:not-approved :i64]
          [:double-disb :i64]
          [:afford-applicable :i64]
          [:afford-total :i64]
          [:afford-income :i64]
          [:confidence-x100 :i64]
          [:actuation :i64]]]
        proposal
        :evidence-incomplete)))
     (or2
      (norm-flag
       (record-get
        [:record
         :credit.kernels/proposal
         [[:spec-missing :i64]
          [:evidence-incomplete :i64]
          [:not-approved :i64]
          [:double-disb :i64]
          [:afford-applicable :i64]
          [:afford-total :i64]
          [:afford-income :i64]
          [:confidence-x100 :i64]
          [:actuation :i64]]]
        proposal
        :not-approved))
      (norm-flag
       (record-get
        [:record
         :credit.kernels/proposal
         [[:spec-missing :i64]
          [:evidence-incomplete :i64]
          [:not-approved :i64]
          [:double-disb :i64]
          [:afford-applicable :i64]
          [:afford-total :i64]
          [:afford-income :i64]
          [:confidence-x100 :i64]
          [:actuation :i64]]]
        proposal
        :double-disb))))
    (affordability-exceeded
     (record-get
      [:record
       :credit.kernels/proposal
       [[:spec-missing :i64]
        [:evidence-incomplete :i64]
        [:not-approved :i64]
        [:double-disb :i64]
        [:afford-applicable :i64]
        [:afford-total :i64]
        [:afford-income :i64]
        [:confidence-x100 :i64]
        [:actuation :i64]]]
      proposal
      :afford-applicable)
     (record-get
      [:record
       :credit.kernels/proposal
       [[:spec-missing :i64]
        [:evidence-incomplete :i64]
        [:not-approved :i64]
        [:double-disb :i64]
        [:afford-applicable :i64]
        [:afford-total :i64]
        [:afford-income :i64]
        [:confidence-x100 :i64]
        [:actuation :i64]]]
      proposal
      :afford-total)
     (record-get
      [:record
       :credit.kernels/proposal
       [[:spec-missing :i64]
        [:evidence-incomplete :i64]
        [:not-approved :i64]
        [:double-disb :i64]
        [:afford-applicable :i64]
        [:afford-total :i64]
        [:afford-income :i64]
        [:confidence-x100 :i64]
        [:actuation :i64]]]
      proposal
      :afford-income))),
   :param-types [[:ref :credit.kernels/proposal]]}
  {:name verdict-code,
   :params [proposal],
   :result :i64,
   :effects #{},
   :body
   (if
    (= 1 (hard-violation proposal))
    2
    (if
     (=
      1
      (or2
       (confidence-low
        (record-get
         [:record
          :credit.kernels/proposal
          [[:spec-missing :i64]
           [:evidence-incomplete :i64]
           [:not-approved :i64]
           [:double-disb :i64]
           [:afford-applicable :i64]
           [:afford-total :i64]
           [:afford-income :i64]
           [:confidence-x100 :i64]
           [:actuation :i64]]]
         proposal
         :confidence-x100))
       (norm-flag
        (record-get
         [:record
          :credit.kernels/proposal
          [[:spec-missing :i64]
           [:evidence-incomplete :i64]
           [:not-approved :i64]
           [:double-disb :i64]
           [:afford-applicable :i64]
           [:afford-total :i64]
           [:afford-income :i64]
           [:confidence-x100 :i64]
           [:actuation :i64]]]
         proposal
         :actuation))))
     1
     0)),
   :param-types [[:ref :credit.kernels/proposal]]}
  {:name op-write-enabled,
   :params [phase op],
   :result :i64,
   :effects #{},
   :body
   (if
    (= phase 1)
    (if (= op 1) 1 0)
    (if
     (= phase 2)
     (if (= op 1) 1 (if (= op 2) 1 (if (= op 3) 1 0)))
     (if
      (= phase 3)
      (if
       (= op 1)
       1
       (if
        (= op 2)
        1
        (if (= op 3) 1 (if (= op 4) 1 (if (= op 5) 1 0)))))
      0))),
   :param-types [:i64 :i64]}
  {:name op-auto-enabled,
   :params [phase op],
   :result :i64,
   :effects #{},
   :body (if (= phase 3) (if (= op 1) 1 0) 0),
   :param-types [:i64 :i64]}
  {:name phase-disposition,
   :params [phase op governor-disposition],
   :result :i64,
   :effects #{},
   :body
   (if
    (= governor-disposition 2)
    2
    (if
     (= op 0)
     governor-disposition
     (if
      (= 0 (op-write-enabled phase op))
      2
      (if
       (= governor-disposition 0)
       (if (= 1 (op-auto-enabled phase op)) 0 1)
       governor-disposition)))),
   :param-types [:i64 :i64 :i64]}
  {:name phase-reason,
   :params [phase op governor-disposition],
   :result :i64,
   :effects #{},
   :body
   (if
    (= governor-disposition 2)
    0
    (if
     (= op 0)
     0
     (if
      (= 0 (op-write-enabled phase op))
      1
      (if
       (= governor-disposition 0)
       (if (= 1 (op-auto-enabled phase op)) 0 2)
       0)))),
   :param-types [:i64 :i64 :i64]}],
 :oracle-value nil,
 :schema-identities
 {:credit.kernels/proposal
  "84a84781853c4e6e30eea86ecc96834d0f0e9454af3214f85b55c19f6917dcdb"},
 :exports
 [confidence-floor-x100
  affordability-ceiling-x100
  norm-flag
  confidence-low
  affordability-exceeded
  hard-violation
  verdict-code
  op-write-enabled
  op-auto-enabled
  phase-disposition
  phase-reason],
 :schemas
 {:credit.kernels/proposal
  [:record
   :credit.kernels/proposal
   [[:spec-missing :i64]
    [:evidence-incomplete :i64]
    [:not-approved :i64]
    [:double-disb :i64]
    [:afford-applicable :i64]
    [:afford-total :i64]
    [:afford-income :i64]
    [:confidence-x100 :i64]
    [:actuation :i64]]]},
 :effects #{},
 :blocks [],
 :entry nil}
)
